### ISSUE TITLE
Vercel deploy help

### ISSUE THREAD

**Issue by no-usernamefr** [zardoy/prismarine-web-client#172]
When building using Vercel, I get these errors:
```
`.../.pnpm/gl@6.0.2/node_modules/gl install: gyp ERR! configure error 

.../.pnpm/gl@6.0.2/node_modules/gl install: gyp ERR! stack Error: `gyp` failed with exit code: 1
    at error (file://./node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file://./node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)
    at file://./node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24822:26

Error: Command "storybook build" exited with 1
`
```
Is this a configuration issue? Am I doing something wrong? 
I forked this repo, and then uploaded the _next_ branch to Vercel, it auto selected the storybook framework, I also tried it with next.js framework, but with no success for either. Do I need to be using a different build command? I just let Vercel auto pick the command.

**Comment by zardoy** [comment]
Sorry for the delay, I'll look into the issue within next 30min, if there is an issue with storybook and you don't need it, you can skip this build step

**Comment by zardoy** [comment]
Please see the reference: https://github.com/zardoy/minecraft-web-client/actions/runs/10206948629/job/28240815185

I'm getting no issues for the whole build pipeline. If you have local build issues try docker container!

**Comment by no-usernamefr** [comment]
> Please see the reference: https://github.com/zardoy/minecraft-web-client/actions/runs/10206948629/job/28240815185
> 
> I'm getting no issues for the whole build pipeline. If you have local build issues try docker container!

Thank you for replying, this worked in a docker container locally. I would like to know exactly what settings you used to import your repo.
 ![image](https://github.com/user-attachments/assets/4f930e24-8d25-4e9f-8723-58b73582ea8c)
I tried starting a new build with the config: pnpm storybook build, and prod as the output destination. It's been building for 20 minutes now, and the vercel build is not showing in GitHub actions on my forked repo. On the vercel website, it shows its still building

**Comment by no-usernamefr** [comment]
This is where the build gets stuck at storybook dev -p 6006 "build"
@storybook/cli v7.4.6
info => Starting manager..
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 7.4.6 for react-vite started           │
│   564 ms for manager and 4.05 s for preview        │
│                                                    │
│    Local:            http://localhost:6006/        │
│    On your network:  http://192.168.6.170:6006/    │
│                                                    │
╰────────────────────────────────────────────────────╯
attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

**Comment by zardoy** [comment]
> I tried starting a new build with the config: pnpm storybook build, and prod as the output destination. It's been building for 20 minutes now, and the vercel build is not showing in GitHub actions on my forked repo. On the vercel website, it shows its still building

Instead of figuring out build issues on vercel, use GitHub actions to deploy instead instead: https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

everything is already configured you just need to handle this part from guide: Inside GitHub, add VERCEL_TOKEN, VERCEL_ORG_ID, and VERCEL_PROJECT_ID as [secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets). Google how to find these.

**Comment by no-usernamefr** [comment]
> > I tried starting a new build with the config: pnpm storybook build, and prod as the output destination. It's been building for 20 minutes now, and the vercel build is not showing in GitHub actions on my forked repo. On the vercel website, it shows its still building
> 
> Instead of figuring out build issues on vercel, use GitHub actions to deploy instead instead: https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
> 
> everything is already configured you just need to handle this part from guide: Inside GitHub, add VERCEL_TOKEN, VERCEL_ORG_ID, and VERCEL_PROJECT_ID as [secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets). Google how to find these.

I was able to successfully deploy, I'm sorry if I wasted time. I wasn't sure if it was an issue with this project, or an issue with how I was trying to deploy to vercel. Thank you
