### ISSUE TITLE
Can this client log in with a Microsoft account?

### ISSUE THREAD

**Issue by Taihiroooooo** [zardoy/prismarine-web-client#185]
Can this client log in with a Microsoft account? If possible please tell me how

**Comment by zardoy** [comment]
> If possible please tell me how

No you have to figure out yourself. Sorry.

**Comment by zardoy** [comment]
regression was fixed by https://github.com/zardoy/minecraft-web-client/commit/3a646121ed0008b2773914328a5c5c08a3feae6a will be released soon
