### ISSUE TITLE
Cannot create new seeds on iOS

### ISSUE THREAD

**Issue by MarmeladeTheCat** [zardoy/prismarine-web-client#212]
I tried making a new seed (tried multiple versions- 1.8, 1.14, 1.20) and every time the “create world” button was  dark grey and can’t be pressed. I have enough space to hold the world, but still can’t create it.

**Comment by zardoy** [comment]
New seeds are not being dropped from the crops as it's not supported server-side yet. Just take the seeds from the creative menu (JEI).

**Comment by MarmeladeTheCat** [comment]
Seed as in MC world, not the crop item.
![IMG_0108](https://github.com/user-attachments/assets/64bf828d-8de8-4b05-8622-2d1c472be91f)

**Comment by zardoy** [comment]
There is no seed input to enter in the provided screenshot. And you obviously have to enter a name of a new world so the create button is available for you

**Comment by zardoy** [comment]
@MarmeladeTheCat whats status
