### ISSUE TITLE
make new links

### ISSUE THREAD

**Issue by ftgyhuj456** [zardoy/prismarine-web-client#226]
its blocked

**Comment by zardoy** [comment]
wdym? provide more info

**Comment by zardoy** [comment]
@ftgyhuj456

**Comment by zardoy** [comment]
@ftgyhuj456 any suggestions? please need your feedback

**Comment by zardoy** [comment]
can now deploy yourself with koyeb (see button in readme), also you can join our discord server for the full list of links: https://discord.gg/QHtx8M5Zkx
