### ISSUE TITLE
mcraft.fun not displaying wooden_axe when player is holding

### ISSUE THREAD

**Issue by rohanpaleja27** [zardoy/prismarine-web-client#234]
Hi, 

I was attempting to play MC using mcraft.fun and noticed that only certain objects are visible when holding. Is this an intended feature?

Thanks,

**Comment by zardoy** [comment]
Yes.

**Comment by rohanpaleja27** [comment]
Thanks for the clarification. I'll close this issue.

**Comment by zardoy** [comment]
duplicate of https://github.com/zardoy/minecraft-web-client/issues/229
