### ISSUE TITLE
Make the viewer its own package

### ISSUE THREAD

**Issue by mannyc2** [zardoy/prismarine-web-client#236]
Would love to use it on a personal project but has proven to be difficult to extract just the prismarine-viewer logic & render world data off streamed world data

**Comment by zardoy** [comment]
What is your case? Do you want it to be used with your mineflayer bot as a plugin? I can try to provide a better solution that would be easier for me and you to use

**Comment by zardoy** [comment]
@wozhendeai do you still need it? Can you elaborate?

**Comment by mannyc2** [comment]
Yeah I still need it. For example, I was particularly struggling with trying to setup a mineflayer bot using your viewer/world rendering implementation. I can provide an example of what I tried if you want. 

I was streaming world data from a mineflayer bot and attempting to render it on a react app but I couldn't get it to work

**Comment by zardoy** [comment]
I will make a callback url support on mcraft.fun and mineflayer plugin for it. It will be redirecting you to mcraft.fun with the special link so the website will connect to your plugin via websocket that would stream world data to website. Would it be okay for you?

**Comment by zardoy** [comment]
@wozhendeai thats my plan. Would it work for you?

**Comment by mannyc2** [comment]
Yeah that would be awesome, thanks

**Comment by zardoy** [comment]
Ok, just tracking the task for now

**Comment by zardoy** [comment]
@wozhendeai you can test it now https://github.com/zardoy/mcraft-fun-mineflayer-plugin

**Comment by zardoy** [comment]
> Yeah that would be awesome, thanks

@wozhendeai it was done in this package: https://npmjs.com/mcraft-fun-mineflayer. if s.mcraft.fun doesn't load for you try s.pcm.gg , thanks!

**Comment by mannyc2** [comment]
thanks!! Working with it now

**Comment by zardoy** [comment]
> thanks!! Working with it now

@wozhendeai Don't you mind sharing a screenshot or video if it works in your case? I would highly appreciate it, will use as showcase if you don't mind (no worries I will attach the credits)
