### ISSUE TITLE
Default proxy url?

### ISSUE THREAD

**Issue by zardoy** [zardoy/prismarine-web-client#3]
Seems the proxy from <https://d60kl4rmeuiuq.cloudfront.net/> works well. ~~Would be awesome to have our own proxy servers or at least specify some other in the defaults.~~ Already got an official default proxy. Issue resolved.

**Comment by gwhizoftv** [comment]
Is there a release or deployment kit for the proxy @zardoy  ?

**Comment by zardoy** [comment]
What do you mean by development kit? Just `pnpm install` and `pnpm start`. And btw seems on current you can't connect to sever, here is backup https://prismarine-web-client-7azvzjgqy-zardoy.vercel.app

**Comment by gwhizoftv** [comment]
SOerry, I cannot find which repo is for the proxy @zardoy Appreciate a pointer or doc!

**Comment by zardoy** [comment]
> SOerry, I cannot find which repo is for the proxy @zardoy Appreciate a pointer or doc!

Hey! The proxy is just a single file https://github.com/zardoy/prismarine-web-client/blob/main/server.js that you can start. It doesn't really matter what repo you pick: original or this one. So after installing packages just run `node server.js` and that's it! You can connect to your proxy on port 8080 e.g. localhost:8080 . Feel free to ask more questions if something unclear. You can ask here, on the discord server, or even dm me!

**Comment by zardoy** [comment]
Uptime proxy status https://uptime.statuscake.com/?TestID=Jv9AtZKMrz
