### ISSUE TITLE
 Incorrect calculation of resource pack installation progress

### ISSUE THREAD

**Issue by MrZillaGold** [zardoy/prismarine-web-client#55]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Funded-%2300A156.svg" />](https://oss.issuehunt.io/r/zardoy/prismarine-web-client/issues/55)

<img width="1110" alt="Снимок экрана 2024-01-13 в 21 06 44" src="https://github.com/zardoy/prismarine-web-client/assets/42776347/c6047042-1aba-49a5-8c34-cb5fc6f398fc">

https://mcraft.fun/?texturepack=https%3A%2F%2Fzardoy.site%2Fwp-content%2F%3Ffile%3Duploads%2F2023%2F09%2FPollachiusv1.0.0for1.8.zip

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars.githubusercontent.com/u/46503702?v=4' alt='zardoy' width=24 height=24> zardoy](https://oss.issuehunt.io/u/zardoy) ($10.00)

### Submitted pull Requests
- [#74 fix: issue #55: Incorrect calculation of resource pack installation progress](https://oss.issuehunt.io/r/zardoy/prismarine-web-client/pull/74)
---

### Tips

- Checkout the [Issuehunt explorer](https://oss.issuehunt.io/r/zardoy/prismarine-web-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://oss.issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by zardoy** [comment]
looks fun 😆 though ik it since i first pushed it, but i was too focused on the fact that it "just works", feel free to look into why it happens. I will probably fix it on browserfs update, but who knows when it will happen
