### ISSUE TITLE
Broken support for 1.20.4

### ISSUE THREAD

**Issue by Dimka380** [zardoy/prismarine-web-client#80]
I can't join a server because it needs me to be on 1.20.4 which the client doesn't support, Can you update the bot version, please?
the site I'm experiencing it on is [mcraft.fun](https://mcraft.fun/).

**Comment by zardoy** [comment]
Yes mcraft.fun is the main website of this repo with the latest release deployment and indeed we need to updated the mineflayer to support it. Do you does mineflayer support 1.20.4  now?

**Comment by zardoy** [comment]
@Dimka380 It is now available on https://s.mcraft.fun . If everything is fine it will be released soon.

**Comment by Dimka380** [comment]
Come on. The link you provided (s.mcraft.fun) does not support 1.20.4
![image](https://github.com/zardoy/prismarine-web-client/assets/90362202/ec31d4ab-7652-494a-b209-19d95f68810e)

**Comment by zardoy** [comment]
@Dimka380 Are you sure you still can't connect to 1.20.4 servers? This suggestion list shows only fully tested versions

**Comment by Dimka380** [comment]
> @Dimka380 Are you sure you still can't connect to 1.20.4 servers? This suggestion list shows only fully tested versions

I can connect, but it seems to keep pushing me to where I spawned, and I can't chat.
Then after about 1 minute, it gives me this error:
"__The Minecraft server kicked you. Kick reason: [object Object]__"
The proxy I used is: proxy.mcraft.fun:443

**Comment by zardoy** [comment]
> I can connect, but it seems to keep pushing me to where I spawned, and I can't chat.
> Then after about 1 minute, it gives me this error:

Sorry for the delay, I actually tested 1.20.4 support with the vanilla server when I pushed it. Maybe that server is not vanilla? Also what is the kick reason (objects are displayed in devtools console)?

**Comment by zardoy** [comment]
Indeed there are issues with chat
